name: "Bug"
description: "Template for reporting bugs or unexpected system behaviors."
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Bug Report Details

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Clear description of the issue."
      placeholder: "Describe the unexpected behavior..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to recreate the bug."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected vs Actual Behavior"
      placeholder: |
        - Expected: ...
        - Actual: ...
    validations:
      required: true
